### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Meff1u** [therealOri/GeoEye#1]
after typing `pip3 install requests os` in cmd

ERROR: Could not find a version that satisfies the requirement os (from versions: none)
ERROR: No matching distribution found for os

**Comment by therealOri** [comment]
> after typing `pip3 install requests os` in cmd
> 
> ERROR: Could not find a version that satisfies the requirement os (from versions: none) ERROR: No matching distribution found for os

`os` doesn't need to be installed and thank you for letting me know that it was left in the command. (readME has been updated)
